import type { MaterialMeta, MaterialGroup } from '@/types';

/** 物料分组定义（参照扣子：布局/输入/展示/自定义） */
export const materialGroups: { key: MaterialGroup; name: string }[] = [
  { key: 'layout', name: '布局组件' },
  { key: 'input', name: '输入组件' },
  { key: 'display', name: '展示组件' },
  { key: 'custom', name: '自定义组件' },
];

/** 展示类组件通用事件（加载/点击/双击/移入/移出） */
const DISPLAY_EVENTS = ['load', 'click', 'doubleClick', 'mouseEnter', 'mouseLeave'] as const;

/** 输入类组件事件（加载/聚焦/失焦/值变化） */
const INPUT_EVENTS = ['load', 'focus', 'blur', 'change'] as const;

/** 通用属性：组件名称（已在信息头编辑，不重复） */
/** 通用属性：隐藏（可见性） */
const commonPropFields = [
  { key: 'hidden', label: '隐藏', type: 'switch' as const, default: false, group: 'props' as const },
];

/** 物料注册表：id → 元信息 */
export const materialRegistry: Record<string, MaterialMeta> = {
  // ===== 展示组件 =====
  text: {
    id: 'text',
    name: '文本',
    group: 'display',
    icon: 'Document',
    defaultProps: { content: '这是一段文本', fontSize: 14, fontWeight: '400', color: '#1f2329', align: 'left' },
    defaultSize: { width: 320, height: 40 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'content', label: '内容', type: 'textarea', default: '这是一段文本', group: 'props' },
      { key: 'fontSize', label: '字号', type: 'number', default: 14, group: 'props' },
      {
        key: 'fontWeight',
        label: '字重',
        type: 'select',
        default: '400',
        options: [
          { label: '常规', value: '400' },
          { label: '中等', value: '500' },
          { label: '加粗', value: '600' },
          { label: '特粗', value: '700' },
        ],
        group: 'props',
      },
      { key: 'color', label: '文字颜色', type: 'color', default: '#1f2329', group: 'props' },
      {
        key: 'align',
        label: '对齐',
        type: 'select',
        default: 'left',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
        group: 'props',
      },
      ...commonPropFields,
    ],
  },

  button: {
    id: 'button',
    name: '按钮',
    group: 'display',
    icon: 'Pointer',
    defaultProps: { text: '按钮', type: 'primary', size: 'default', disabled: false, loading: false, plain: false, round: false },
    defaultSize: { width: 120, height: 40 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'text', label: '按钮文字', type: 'input', default: '按钮', group: 'props' },
      {
        key: 'type',
        label: '按钮类型',
        type: 'select',
        default: 'primary',
        options: [
          { label: '主要', value: 'primary' },
          { label: '默认', value: 'default' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
        group: 'props',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: 'props',
      },
      { key: 'plain', label: '朴素按钮', type: 'switch', default: false, group: 'props' },
      { key: 'round', label: '圆角按钮', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'loading', label: '加载态', type: 'switch', default: false, group: 'props' },
      { key: 'icon', label: '图标', type: 'iconPicker', default: '', group: 'props' },
      ...commonPropFields,
    ],
  },

  // ===== 布局组件 =====
  container: {
    id: 'container',
    name: '容器',
    group: 'layout',
    icon: 'Grid',
    isContainer: true,
    defaultProps: { direction: 'vertical', justify: 'flex-start', align: 'flex-start', gap: 12, padding: 16, background: '#ffffff', hidden: false },
    defaultSize: { width: 480, height: 200 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'direction',
        label: '排列方向',
        type: 'select',
        default: 'vertical',
        options: [
          { label: '纵向', value: 'vertical' },
          { label: '横向', value: 'horizontal' },
        ],
        group: 'props',
      },
      {
        key: 'justify',
        label: '主轴对齐',
        type: 'select',
        default: 'flex-start',
        options: [
          { label: '起始', value: 'flex-start' },
          { label: '居中', value: 'center' },
          { label: '末尾', value: 'flex-end' },
          { label: '两端', value: 'space-between' },
          { label: '均匀', value: 'space-around' },
        ],
        group: 'props',
      },
      {
        key: 'align',
        label: '交叉对齐',
        type: 'select',
        default: 'flex-start',
        options: [
          { label: '起始', value: 'flex-start' },
          { label: '居中', value: 'center' },
          { label: '末尾', value: 'flex-end' },
          { label: '拉伸', value: 'stretch' },
        ],
        group: 'props',
      },
      { key: 'gap', label: '间距', type: 'number', default: 12, group: 'props' },
      { key: 'padding', label: '内边距', type: 'number', default: 16, group: 'props' },
      { key: 'background', label: '背景色', type: 'color', default: '#ffffff', group: 'props' },
      ...commonPropFields,
    ],
  },

  // 布局组件（续）
  columns: {
    id: 'columns',
    name: '分栏',
    group: 'layout',
    icon: 'Grid',
    isContainer: true,
    defaultProps: { columns: 2, gap: 12, background: 'transparent' },
    defaultSize: { width: 480, height: 120 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'columns', label: '列数', type: 'number', default: 2, group: 'props' },
      { key: 'gap', label: '列间距', type: 'number', default: 12, group: 'props' },
      { key: 'background', label: '背景色', type: 'color', default: 'transparent', group: 'props' },
      ...commonPropFields,
    ],
  },

  card: {
    id: 'card',
    name: '卡片',
    group: 'layout',
    icon: 'Postcard',
    isContainer: true,
    defaultProps: { title: '卡片标题', shadow: 'hover', padding: 16 },
    defaultSize: { width: 480, height: 200 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'title', label: '标题', type: 'input', default: '卡片标题', group: 'props' },
      {
        key: 'shadow',
        label: '阴影',
        type: 'select',
        default: 'hover',
        options: [
          { label: '常显', value: 'always' },
          { label: '悬浮', value: 'hover' },
          { label: '无', value: 'never' },
        ],
        group: 'props',
      },
      { key: 'padding', label: '内边距', type: 'number', default: 16, group: 'props' },
      ...commonPropFields,
    ],
  },

  tabs: {
    id: 'tabs',
    name: '标签页',
    group: 'layout',
    icon: 'Files',
    isContainer: true,
    defaultProps: {
      items: '[{"label":"标签一","content":"内容一"},{"label":"标签二","content":"内容二"}]',
      type: '',
      position: 'top',
    },
    defaultSize: { width: 480, height: 200 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '标签数据(JSON)',
        type: 'textarea',
        default: '[{"label":"标签一","content":"内容一"},{"label":"标签二","content":"内容二"}]',
        group: 'props',
      },
      {
        key: 'type',
        label: '风格',
        type: 'select',
        default: '',
        options: [
          { label: '默认', value: '' },
          { label: '卡片', value: 'card' },
          { label: '边框卡片', value: 'border-card' },
        ],
        group: 'props',
      },
      {
        key: 'position',
        label: '位置',
        type: 'select',
        default: 'top',
        options: [
          { label: '顶部', value: 'top' },
          { label: '右侧', value: 'right' },
          { label: '底部', value: 'bottom' },
          { label: '左侧', value: 'left' },
        ],
        group: 'props',
      },
      ...commonPropFields,
    ],
  },

  collapse: {
    id: 'collapse',
    name: '折叠面板',
    group: 'layout',
    icon: 'Operation',
    isContainer: true,
    defaultProps: {
      items: '[{"title":"面板一","content":"内容一"},{"title":"面板二","content":"内容二"}]',
      accordion: false,
    },
    defaultSize: { width: 480, height: 160 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '面板数据(JSON)',
        type: 'textarea',
        default: '[{"title":"面板一","content":"内容一"},{"title":"面板二","content":"内容二"}]',
        group: 'props',
      },
      { key: 'accordion', label: '手风琴模式', type: 'switch', default: false, group: 'props' },
      ...commonPropFields,
    ],
  },

  vlist: {
    id: 'vlist',
    name: '纵向列表',
    group: 'layout',
    icon: 'List',
    isContainer: true,
    defaultProps: {
      items: '[{"title":"列表项一","desc":"这是列表项描述","image":""},{"title":"列表项二","desc":"这是列表项描述","image":""},{"title":"列表项三","desc":"这是列表项描述","image":""}]',
      gap: 8,
      showImage: true,
    },
    defaultSize: { width: 360, height: 220 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '列表数据(JSON)',
        type: 'textarea',
        default: '[{"title":"列表项一","desc":"描述","image":""}]',
        group: 'props',
      },
      { key: 'gap', label: '间距', type: 'number', default: 8, group: 'props' },
      { key: 'showImage', label: '显示图片', type: 'switch', default: true, group: 'props' },
      ...commonPropFields,
    ],
  },

  hlist: {
    id: 'hlist',
    name: '横向列表',
    group: 'layout',
    icon: 'Document',
    isContainer: true,
    defaultProps: {
      items: '[{"title":"卡片一","image":""},{"title":"卡片二","image":""},{"title":"卡片三","image":""}]',
      gap: 12,
      cardWidth: 140,
    },
    defaultSize: { width: 480, height: 140 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '列表数据(JSON)',
        type: 'textarea',
        default: '[{"title":"卡片一","image":""}]',
        group: 'props',
      },
      { key: 'gap', label: '间距', type: 'number', default: 12, group: 'props' },
      { key: 'cardWidth', label: '卡片宽度', type: 'number', default: 140, group: 'props' },
      ...commonPropFields,
    ],
  },

  gridlist: {
    id: 'gridlist',
    name: '宫格列表',
    group: 'layout',
    icon: 'Grid',
    isContainer: true,
    defaultProps: {
      items: '[{"title":"宫格一","icon":"Menu","image":""},{"title":"宫格二","icon":"Grid","image":""},{"title":"宫格三","icon":"Picture","image":""},{"title":"宫格四","icon":"Star","image":""}]',
      columns: 3,
      gap: 12,
    },
    defaultSize: { width: 360, height: 200 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '宫格数据(JSON)',
        type: 'textarea',
        default: '[{"title":"宫格一","icon":"Menu","image":""}]',
        group: 'props',
      },
      { key: 'columns', label: '列数', type: 'number', default: 3, group: 'props' },
      { key: 'gap', label: '间距', type: 'number', default: 12, group: 'props' },
      ...commonPropFields,
    ],
  },

  waterfall: {
    id: 'waterfall',
    name: '瀑布流',
    group: 'layout',
    icon: 'Grid',
    isContainer: true,
    defaultProps: {
      items: '[{"title":"卡片一","image":"","height":160},{"title":"卡片二","image":"","height":120},{"title":"卡片三","image":"","height":180},{"title":"卡片四","image":"","height":100},{"title":"卡片五","image":"","height":140},{"title":"卡片六","image":"","height":160}]',
      columns: 2,
      gap: 12,
    },
    defaultSize: { width: 360, height: 280 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '瀑布流数据(JSON)',
        type: 'textarea',
        default: '[{"title":"卡片一","image":"","height":160}]',
        group: 'props',
      },
      { key: 'columns', label: '列数', type: 'number', default: 2, group: 'props' },
      { key: 'gap', label: '间距', type: 'number', default: 12, group: 'props' },
      ...commonPropFields,
    ],
  },

  // ===== 输入组件 =====
  input: {
    id: 'input',
    name: '输入框',
    group: 'input',
    icon: 'Edit',
    defaultProps: { label: '输入框', placeholder: '请输入', required: false, disabled: false, clearable: true, maxlength: 0, prefix: '', suffix: '' },
    defaultSize: { width: 320, height: 64 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '输入框', group: 'props' },
      { key: 'placeholder', label: '占位提示', type: 'input', default: '请输入', group: 'props' },
      { key: 'required', label: '是否必填', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'clearable', label: '可清空', type: 'switch', default: true, group: 'props' },
      { key: 'maxlength', label: '最大长度(0不限)', type: 'number', default: 0, group: 'props' },
      { key: 'prefix', label: '前缀', type: 'input', default: '', group: 'props' },
      { key: 'suffix', label: '后缀', type: 'input', default: '', group: 'props' },
      ...commonPropFields,
    ],
  },

  textarea: {
    id: 'textarea',
    name: '文本域',
    group: 'input',
    icon: 'EditPen',
    defaultProps: { label: '文本域', placeholder: '请输入', required: false, disabled: false, rows: 3, maxlength: 0 },
    defaultSize: { width: 320, height: 120 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '文本域', group: 'props' },
      { key: 'placeholder', label: '占位提示', type: 'input', default: '请输入', group: 'props' },
      { key: 'required', label: '是否必填', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'rows', label: '行数', type: 'number', default: 3, group: 'props' },
      { key: 'maxlength', label: '最大长度(0不限)', type: 'number', default: 0, group: 'props' },
      ...commonPropFields,
    ],
  },

  number: {
    id: 'number',
    name: '数字输入',
    group: 'input',
    icon: 'Histogram',
    defaultProps: { label: '数字', placeholder: '请输入', required: false, disabled: false, min: 0, max: 999, step: 1, defaultValue: 0 },
    defaultSize: { width: 320, height: 64 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '数字', group: 'props' },
      { key: 'placeholder', label: '占位提示', type: 'input', default: '请输入', group: 'props' },
      { key: 'required', label: '是否必填', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'min', label: '最小值', type: 'number', default: 0, group: 'props' },
      { key: 'max', label: '最大值', type: 'number', default: 999, group: 'props' },
      { key: 'step', label: '步长', type: 'number', default: 1, group: 'props' },
      { key: 'defaultValue', label: '默认值', type: 'number', default: 0, group: 'props' },
      ...commonPropFields,
    ],
  },

  select: {
    id: 'select',
    name: '下拉选择',
    group: 'input',
    icon: 'ArrowDown',
    defaultProps: { label: '下拉选择', placeholder: '请选择', required: false, disabled: false, clearable: true, multiple: false, options: [{ label: '选项1', value: '1' }, { label: '选项2', value: '2' }] },
    defaultSize: { width: 320, height: 64 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '下拉选择', group: 'props' },
      { key: 'placeholder', label: '占位提示', type: 'input', default: '请选择', group: 'props' },
      { key: 'required', label: '是否必填', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'clearable', label: '可清空', type: 'switch', default: true, group: 'props' },
      { key: 'multiple', label: '多选', type: 'switch', default: false, group: 'props' },
      { key: 'options', label: '选项列表', type: 'optionsEditor', default: [], group: 'props' },
      ...commonPropFields,
    ],
  },

  radio: {
    id: 'radio',
    name: '单选组',
    group: 'input',
    icon: 'CircleCheck',
    defaultProps: { label: '单选', required: false, disabled: false, options: [{ label: '选项1', value: '1' }, { label: '选项2', value: '2' }] },
    defaultSize: { width: 320, height: 80 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '单选', group: 'props' },
      { key: 'required', label: '是否必填', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'options', label: '选项列表', type: 'optionsEditor', default: [], group: 'props' },
      ...commonPropFields,
    ],
  },

  checkbox: {
    id: 'checkbox',
    name: '多选组',
    group: 'input',
    icon: 'Select',
    defaultProps: { label: '多选', required: false, disabled: false, options: [{ label: '选项1', value: '1' }, { label: '选项2', value: '2' }] },
    defaultSize: { width: 320, height: 80 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '多选', group: 'props' },
      { key: 'required', label: '是否必填', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'options', label: '选项列表', type: 'optionsEditor', default: [], group: 'props' },
      ...commonPropFields,
    ],
  },

  switch: {
    id: 'switch',
    name: '开关',
    group: 'input',
    icon: 'Switch',
    defaultProps: { label: '开关', disabled: false, activeText: '', inactiveText: '', defaultValue: false },
    defaultSize: { width: 320, height: 48 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '开关', group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'activeText', label: '开启文字', type: 'input', default: '', group: 'props' },
      { key: 'inactiveText', label: '关闭文字', type: 'input', default: '', group: 'props' },
      { key: 'defaultValue', label: '默认值', type: 'switch', default: false, group: 'props' },
      ...commonPropFields,
    ],
  },

  datepicker: {
    id: 'datepicker',
    name: '日期选择',
    group: 'input',
    icon: 'Calendar',
    defaultProps: { label: '日期', placeholder: '请选择日期', required: false, disabled: false, type: 'date', format: 'YYYY-MM-DD' },
    defaultSize: { width: 320, height: 64 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '日期', group: 'props' },
      { key: 'placeholder', label: '占位提示', type: 'input', default: '请选择日期', group: 'props' },
      { key: 'required', label: '是否必填', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        default: 'date',
        options: [
          { label: '日期', value: 'date' },
          { label: '日期时间', value: 'datetime' },
          { label: '年份', value: 'year' },
          { label: '月份', value: 'month' },
          { label: '日期范围', value: 'daterange' },
        ],
        group: 'props',
      },
      { key: 'format', label: '格式', type: 'input', default: 'YYYY-MM-DD', group: 'props' },
      ...commonPropFields,
    ],
  },

  rate: {
    id: 'rate',
    name: '评分',
    group: 'input',
    icon: 'StarFilled',
    defaultProps: { label: '评分', disabled: false, max: 5, allowHalf: true, defaultValue: 0 },
    defaultSize: { width: 320, height: 48 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '评分', group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'max', label: '最大星数', type: 'number', default: 5, group: 'props' },
      { key: 'allowHalf', label: '允许半星', type: 'switch', default: true, group: 'props' },
      { key: 'defaultValue', label: '默认值', type: 'number', default: 0, group: 'props' },
      ...commonPropFields,
    ],
  },

  slider: {
    id: 'slider',
    name: '滑块',
    group: 'input',
    icon: 'Minus',
    defaultProps: { label: '滑块', disabled: false, min: 0, max: 100, step: 1, defaultValue: 0 },
    defaultSize: { width: 320, height: 48 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '滑块', group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'min', label: '最小值', type: 'number', default: 0, group: 'props' },
      { key: 'max', label: '最大值', type: 'number', default: 100, group: 'props' },
      { key: 'step', label: '步长', type: 'number', default: 1, group: 'props' },
      { key: 'defaultValue', label: '默认值', type: 'slider', default: 0, min: 0, max: 100, step: 1, group: 'props' },
      ...commonPropFields,
    ],
  },

  upload: {
    id: 'upload',
    name: '文件上传',
    group: 'input',
    icon: 'Upload',
    defaultProps: { label: '上传', disabled: false, multiple: false, limit: 5, accept: '', listType: 'text' },
    defaultSize: { width: 320, height: 100 },
    supportEvents: [...INPUT_EVENTS],
    propertySchema: [
      { key: 'label', label: '标签', type: 'input', default: '上传', group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      { key: 'multiple', label: '多选', type: 'switch', default: false, group: 'props' },
      { key: 'limit', label: '最大数量', type: 'number', default: 5, group: 'props' },
      { key: 'accept', label: '接受类型', type: 'input', default: '', group: 'props' },
      {
        key: 'listType',
        label: '列表样式',
        type: 'select',
        default: 'text',
        options: [
          { label: '文本', value: 'text' },
          { label: '图片', value: 'picture-card' },
          { label: '图片列表', value: 'picture' },
        ],
        group: 'props',
      },
      ...commonPropFields,
    ],
  },

  // ===== 展示组件（续）=====
  heading: {
    id: 'heading',
    name: '标题',
    group: 'display',
    icon: 'Tickets',
    defaultProps: { content: '标题', level: 1, align: 'left', color: '#1f2329' },
    defaultSize: { width: 320, height: 48 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'content', label: '标题内容', type: 'input', default: '标题', group: 'props' },
      {
        key: 'level',
        label: '层级',
        type: 'select',
        default: 1,
        options: [
          { label: 'H1', value: 1 },
          { label: 'H2', value: 2 },
          { label: 'H3', value: 3 },
          { label: 'H4', value: 4 },
          { label: 'H5', value: 5 },
          { label: 'H6', value: 6 },
        ],
        group: 'props',
      },
      {
        key: 'align',
        label: '对齐',
        type: 'select',
        default: 'left',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
        group: 'props',
      },
      { key: 'color', label: '文字颜色', type: 'color', default: '#1f2329', group: 'props' },
      ...commonPropFields,
    ],
  },

  // 展示组件（续）
  image: {
    id: 'image',
    name: '图片',
    group: 'display',
    icon: 'Picture',
    defaultProps: { src: '', alt: '图片', fit: 'cover', radius: 8 },
    defaultSize: { width: 240, height: 160 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'src', label: '图片地址', type: 'input', default: '', group: 'props' },
      { key: 'alt', label: '替代文本', type: 'input', default: '图片', group: 'props' },
      {
        key: 'fit',
        label: '适配模式',
        type: 'select',
        default: 'cover',
        options: [
          { label: '填充', value: 'fill' },
          { label: '覆盖', value: 'cover' },
          { label: '包含', value: 'contain' },
          { label: '无', value: 'none' },
        ],
        group: 'props',
      },
      { key: 'radius', label: '圆角', type: 'number', default: 8, group: 'props' },
      ...commonPropFields,
    ],
  },

  icon: {
    id: 'icon',
    name: '图标',
    group: 'display',
    icon: 'Star',
    defaultProps: { name: 'Star', size: 32, color: '#1f2329' },
    defaultSize: { width: 60, height: 60 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'name', label: '图标', type: 'iconPicker', default: 'Star', group: 'props' },
      { key: 'size', label: '大小', type: 'number', default: 32, group: 'props' },
      { key: 'color', label: '颜色', type: 'color', default: '#1f2329', group: 'props' },
      ...commonPropFields,
    ],
  },

  divider: {
    id: 'divider',
    name: '分割线',
    group: 'display',
    icon: 'Minus',
    defaultProps: { direction: 'horizontal', borderStyle: 'solid', color: '#dcdfe6' },
    defaultSize: { width: 480, height: 20 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'direction',
        label: '方向',
        type: 'select',
        default: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
        group: 'props',
      },
      {
        key: 'borderStyle',
        label: '样式',
        type: 'select',
        default: 'solid',
        options: [
          { label: '实线', value: 'solid' },
          { label: '虚线', value: 'dashed' },
          { label: '点线', value: 'dotted' },
        ],
        group: 'props',
      },
      { key: 'color', label: '颜色', type: 'color', default: '#dcdfe6', group: 'props' },
      ...commonPropFields,
    ],
  },

  link: {
    id: 'link',
    name: '链接',
    group: 'display',
    icon: 'Link',
    defaultProps: { text: '链接', href: '#', type: 'primary', underline: false, disabled: false },
    defaultSize: { width: 120, height: 32 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'text', label: '链接文字', type: 'input', default: '链接', group: 'props' },
      { key: 'href', label: '跳转地址', type: 'input', default: '#', group: 'props' },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        default: 'primary',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '默认', value: 'default' },
        ],
        group: 'props',
      },
      { key: 'underline', label: '下划线', type: 'switch', default: false, group: 'props' },
      { key: 'disabled', label: '禁用', type: 'switch', default: false, group: 'props' },
      ...commonPropFields,
    ],
  },

  table: {
    id: 'table',
    name: '表格',
    group: 'display',
    icon: 'Menu',
    defaultProps: { columns: 3, rows: 3, stripe: true, border: true, size: 'default' },
    defaultSize: { width: 480, height: 200 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'columns', label: '列数', type: 'number', default: 3, group: 'props' },
      { key: 'rows', label: '行数', type: 'number', default: 3, group: 'props' },
      { key: 'stripe', label: '斑马纹', type: 'switch', default: true, group: 'props' },
      { key: 'border', label: '边框', type: 'switch', default: true, group: 'props' },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: 'props',
      },
      ...commonPropFields,
    ],
  },

  list: {
    id: 'list',
    name: '列表',
    group: 'display',
    icon: 'List',
    defaultProps: { items: ['列表项一', '列表项二', '列表项三'], border: true, size: 'default' },
    defaultSize: { width: 320, height: 160 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '列表项(每行一条)',
        type: 'textarea',
        default: '列表项一\n列表项二\n列表项三',
        group: 'props',
      },
      { key: 'border', label: '边框', type: 'switch', default: true, group: 'props' },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: 'props',
      },
      ...commonPropFields,
    ],
  },

  progress: {
    id: 'progress',
    name: '进度条',
    group: 'display',
    icon: 'DataLine',
    defaultProps: { percentage: 50, strokeWidth: 6, showText: true },
    defaultSize: { width: 320, height: 40 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'percentage', label: '百分比', type: 'slider', default: 50, min: 0, max: 100, step: 1, group: 'props' },
      { key: 'strokeWidth', label: '线宽', type: 'number', default: 6, group: 'props' },
      { key: 'showText', label: '显示文字', type: 'switch', default: true, group: 'props' },
      {
        key: 'status',
        label: '状态',
        type: 'select',
        default: '',
        options: [
          { label: '默认', value: '' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '异常', value: 'exception' },
        ],
        group: 'props',
      },
      { key: 'color', label: '颜色', type: 'color', default: '#409eff', group: 'props' },
      ...commonPropFields,
    ],
  },

  badge: {
    id: 'badge',
    name: '徽标',
    group: 'display',
    icon: 'Bell',
    defaultProps: { value: 'New', max: 99, type: 'danger', hidden: false, content: '徽标内容' },
    defaultSize: { width: 120, height: 48 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'value', label: '徽标值', type: 'input', default: 'New', group: 'props' },
      { key: 'max', label: '最大值', type: 'number', default: 99, group: 'props' },
      {
        key: 'type',
        label: '类型',
        type: 'select',
        default: 'danger',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '信息', value: 'info' },
        ],
        group: 'props',
      },
      { key: 'hidden', label: '隐藏', type: 'switch', default: false, group: 'props' },
      { key: 'content', label: '子内容', type: 'input', default: '徽标内容', group: 'props' },
      ...commonPropFields,
    ],
  },

  empty: {
    id: 'empty',
    name: '空状态',
    group: 'display',
    icon: 'Box',
    defaultProps: { description: '暂无数据', imageSize: 80 },
    defaultSize: { width: 320, height: 160 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'description', label: '描述文字', type: 'input', default: '暂无数据', group: 'props' },
      { key: 'imageSize', label: '图标大小', type: 'number', default: 80, group: 'props' },
      ...commonPropFields,
    ],
  },

  pagination: {
    id: 'pagination',
    name: '分页',
    group: 'display',
    icon: 'Document',
    defaultProps: { total: 100, pageSize: 10, layout: 'prev, pager, next', background: true },
    defaultSize: { width: 480, height: 48 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'total', label: '总条数', type: 'number', default: 100, group: 'props' },
      { key: 'pageSize', label: '每页条数', type: 'number', default: 10, group: 'props' },
      {
        key: 'layout',
        label: '布局',
        type: 'select',
        default: 'prev, pager, next',
        options: [
          { label: '简洁', value: 'prev, pager, next' },
          { label: '带跳转', value: 'prev, pager, next, jumper' },
          { label: '带总数', value: 'total, prev, pager, next, jumper' },
          { label: '完整', value: 'total, sizes, prev, pager, next, jumper' },
        ],
        group: 'props',
      },
      { key: 'background', label: '背景色', type: 'switch', default: true, group: 'props' },
      ...commonPropFields,
    ],
  },

  carousel: {
    id: 'carousel',
    name: '轮播图',
    group: 'display',
    icon: 'PictureFilled',
    defaultProps: { items: ['轮播图一', '轮播图二', '轮播图三'], height: '200px', interval: 3000, arrow: 'hover', type: '' },
    defaultSize: { width: 480, height: 220 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      {
        key: 'items',
        label: '轮播项(每行一条，URL或文字)',
        type: 'textarea',
        default: '轮播图一\n轮播图二\n轮播图三',
        group: 'props',
      },
      { key: 'height', label: '高度', type: 'input', default: '200px', group: 'props' },
      { key: 'interval', label: '切换间隔(ms)', type: 'number', default: 3000, group: 'props' },
      {
        key: 'arrow',
        label: '箭头',
        type: 'select',
        default: 'hover',
        options: [
          { label: '常显', value: 'always' },
          { label: '悬浮', value: 'hover' },
          { label: '隐藏', value: 'never' },
        ],
        group: 'props',
      },
      {
        key: 'type',
        label: '模式',
        type: 'select',
        default: '',
        options: [
          { label: '默认', value: '' },
          { label: '卡片', value: 'card' },
        ],
        group: 'props',
      },
      ...commonPropFields,
    ],
  },

  markdown: {
    id: 'markdown',
    name: 'Markdown',
    group: 'display',
    icon: 'EditPen',
    defaultProps: { content: '# 标题\n\n这是一段 **Markdown** 文本，支持 `行内代码` 和 [链接](https://example.com)。\n\n- 列表项一\n- 列表项二\n\n> 引用文本' },
    defaultSize: { width: 480, height: 240 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'content', label: 'Markdown 内容', type: 'textarea', default: '', group: 'props' },
      ...commonPropFields,
    ],
  },

  codeblock: {
    id: 'codeblock',
    name: '代码块',
    group: 'display',
    icon: 'Document',
    defaultProps: { code: "function hello() {\n  console.log('Hello, World!');\n}", language: 'javascript', showLineNumbers: true },
    defaultSize: { width: 480, height: 200 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'code', label: '代码内容', type: 'textarea', default: '', group: 'props' },
      {
        key: 'language',
        label: '语言',
        type: 'select',
        default: 'javascript',
        options: [
          { label: 'JavaScript', value: 'javascript' },
          { label: 'TypeScript', value: 'typescript' },
          { label: 'Python', value: 'python' },
          { label: 'Java', value: 'java' },
          { label: 'Go', value: 'go' },
          { label: 'HTML', value: 'html' },
          { label: 'CSS', value: 'css' },
          { label: 'JSON', value: 'json' },
          { label: 'SQL', value: 'sql' },
          { label: 'Shell', value: 'bash' },
        ],
        group: 'props',
      },
      { key: 'showLineNumbers', label: '行号', type: 'switch', default: true, group: 'props' },
      ...commonPropFields,
    ],
  },

  // 展示组件（续）
  modal: {
    id: 'modal',
    name: '弹窗',
    group: 'display',
    icon: 'Monitor',
    defaultProps: { title: '弹窗标题', width: '500px', content: '弹窗内容区域' },
    defaultSize: { width: 200, height: 48 },
    supportEvents: [...DISPLAY_EVENTS],
    propertySchema: [
      { key: 'title', label: '标题', type: 'input', default: '弹窗标题', group: 'props' },
      { key: 'width', label: '宽度', type: 'input', default: '500px', group: 'props' },
      { key: 'content', label: '内容', type: 'textarea', default: '弹窗内容区域', group: 'props' },
      ...commonPropFields,
    ],
  },
};

/** 按分组获取物料列表 */
export function listMaterialsByGroup(): Record<MaterialGroup, MaterialMeta[]> {
  const result: Record<MaterialGroup, MaterialMeta[]> = {
    layout: [],
    input: [],
    display: [],
    custom: [],
  };
  for (const meta of Object.values(materialRegistry)) {
    result[meta.group].push(meta);
  }
  return result;
}
